kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-rm-343710
  namespace: rm-343710
  selfLink: >-
    /apis/autoscaling/v2beta2/namespaces/rm-343710/horizontalpodautoscalers/hpa-rm-343710
  uid: 0d1773ae-495b-4f41-a219-70b139965f0a
  resourceVersion: '93377679'
  creationTimestamp: '2022-07-09T01:56:52Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-07-09T01:56:52Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v1
      time: '2022-07-09T03:21:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:autoscaling.alpha.kubernetes.io/conditions': {}
            'f:autoscaling.alpha.kubernetes.io/current-metrics': {}
        'f:status':
          'f:currentCPUUtilizationPercentage': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
          'f:lastScaleTime': {}
spec:
  scaleTargetRef:
    kind: Deployment
    name: blog-django-py-git
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
status:
  lastScaleTime: '2022-07-09T12:40:06Z'
  currentReplicas: 1
  desiredReplicas: 1
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: '0'
          averageUtilization: 0
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-07-09T01:57:07Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-07-09T03:42:34Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'True'
      lastTransitionTime: '2022-07-09T13:20:56Z'
      reason: TooFewReplicas
      message: the desired replica count is less than the minimum replica count
